name: CI

on:
  push:
    branches:
    - main

jobs:
  verify:
    name: Verify
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        cache: npm
        cache-dependency-path: package-lock.json
        node-version: 20.x
    - name: Install dependencies
      run: npm ci --no-fund
    - name: Check formatting
      run: npm run fmt:check
    - name: Run tests
      run: npm run test
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]

  dogfood-linux:
    name: Dogfood (ubuntu-latest)
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup Grafana Tanka
      uses: ./
      with:
        tanka-version: 0.26.0
    - name: Show the Grafana Tanka version
      run: |
        version="$(tk --version)"
        echo $version

        if [[ $version =~ "tk version v0.26.0" ]]; then
          exit 1
        fi

  dogfood-windows:
    name: Dogfood (windows-latest)
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup Grafana Tanka
      uses: ./
      with:
        tanka-version: 0.26.0
    - name: Show the Grafana Tanka version
      run: |
        tk.exe --version
