name: PR

on:
  pull_request:
    branches:
    - main
    paths-ignore:
    - .editorconfig
    - .gitignore
    - .prettierignore
    - action.yaml
    - CHANGELOG.md
    - LICENSE.md
    - README.md

jobs:
  verify:
    name: Verify
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        cache: npm
        cache-dependency-path: package-lock.json
        node-version: 20.x
    - name: Install dependencies
      run: npm ci --no-fund
    - name: Check formatting
      run: npm run fmt:check
    - name: Run unit tests
      run: npm run test
